# Generated by Django 3.1.7 on 2021-04-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='buy_now_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='current_highest_bid',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='min_bid_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
