# Generated by Django 3.1.7 on 2021-04-07 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_photo'),
        ('main_app', '0002_listing_seller'),
    ]

    operations = [
    ]
